version: '3'

services:
  php:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      DATABASE_ROOT_PASSWORD: root_password
      DATABASE_NAME: symfony_database
      DATABASE_USER: symfony_user
      DATABASE_PASSWORD: symfony_password
    ports:
      - "3306:3306"
